version: '3'

networks:
  boilerplate-network:
    driver: bridge

volumes:
  boilerplate-mysql:
  boilerplate-redis:

services:
  mysql:
    container_name: boilerplate-mysql
    image: ubuntu/mysql:edge
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    networks:
      - boilerplate-network
    ports:
      - "33061:3306"
    environment:
      - MYSQL_DATABASE=boilerplate
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=boilerplate
      - TZ=UTC
    volumes:
      - boilerplate-mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  redis:
    container_name: boilerplate-redis
    image: redis:4-alpine
    networks:
      - boilerplate-network
    ports:
      - "63791:6379"
    volumes:
      - boilerplate-redis:/data
