server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

  graphql:
    graphiql.enabled: true
    schema.printer.enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peerfund?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      org:
        hibernate:
          format_sql: true
          envers:
            revision_field_name: rev_id
            audit_table_suffix: _histories
            modified_flag_suffix: _modified
            store_data_at_delete: true
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
    show-sql: false
    generate-ddl: false

  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/peerfund?serverTimezone=UTC&characterEncoding=UTF-8
    baseline-version: 1
    user: root
    password: root

  profiles:
    active: local

logging.level:
  org.hibernate.SQL: debug